# Generated by Django 3.1.6 on 2024-01-31 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=1000)),
                ('slug', models.SlugField(blank=True)),
                ('description', models.CharField(max_length=1000)),
                ('prix', models.FloatField()),
                ('image', models.ImageField(null=True, upload_to='uploads/')),
            ],
        ),
    ]
