# Generated by Django 3.1.6 on 2024-02-08 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0002_panier'),
    ]

    operations = [
        migrations.AddField(
            model_name='panier',
            name='prix',
            field=models.FloatField(default=10),
            preserve_default=False,
        ),
    ]
