# Generated by Django 3.1.6 on 2024-02-08 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0003_panier_prix'),
    ]

    operations = [
        migrations.AddField(
            model_name='panier',
            name='libelle',
            field=models.CharField(default=2, max_length=1000),
            preserve_default=False,
        ),
    ]
