# Generated by Django 3.2.18 on 2024-02-08 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0005_auto_20240208_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='panier',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
