# Generated by Django 3.2.18 on 2024-02-13 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0010_auto_20240212_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='message',
            field=models.BinaryField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='offres',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='panier',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
