# Generated by Django 3.2.18 on 2024-02-13 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0011_auto_20240213_0634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='message',
        ),
    ]
