# Generated by Django 3.2.18 on 2024-02-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0013_order_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='QRCODE',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='order',
            name='PUBKEY',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
