# Generated by Django 3.1.6 on 2024-02-13 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0015_auto_20240213_1022'),
    ]

    operations = [
        migrations.CreateModel(
            name='stat_vente',
            fields=[
                ('libelle', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('somme', models.IntegerField()),
            ],
        ),
    ]
