# Generated by Django 3.1.6 on 2024-02-13 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0016_stat_vente'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='HEXA',
            field=models.CharField(blank=True, max_length=3000),
        ),
        migrations.AlterField(
            model_name='order',
            name='QRCODE',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
