# Generated by Django 3.1.6 on 2024-03-07 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0017_auto_20240213_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offres',
            name='libelle',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='panier',
            name='libelle',
            field=models.CharField(max_length=50),
        ),
    ]
